site_name: Hardening + Debian + CIS Benchmarks
site_description: User-friendly and concise Debian CIS Benchmarks
site_author: moisesmsf
repo_url: https://github.com/moisesmsf/hard-debian-benchmark.github.io
theme:
  name: material
  features:
    - content.code.copy
    - content.code.select
    - navigation.instant
    - navigation.tracking
    - navigation.footer
plugins:
  - search:
      lang: en
  - awesome-pages:
      order: asc
      order_by: title
      sort_type: natural
  - tags:
      tags_file: tags.md
markdown_extensions:
  - toc:
      permalink: "#"
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
