site_name: Hardening + Debian + CIS Benchmarks
site_description: User-friendly and concise Debian CIS Benchmarks
site_author: moisesmsf
repo_url: https://github.com/moisesmsf/hard-debian-benchmark.github.io
#nav:
#  - Home: 'index.md'
#  - '1 Initial Setup':
#  - '2 Services':
#  - '3 Network Configuration':
#  - '4 Logging and Auditing':
#  - '5 Access, Authentication and Authorization':
#  - '6 - System Maintenance':
#  - Tags: 'tags.md'
theme:
  name: material
  features:
    - content.code.copy
    - content.code.select
    - navigation.instant
    - navigation.tracking
    - navigation.footer
plugins:
  - search:
      lang: en
  - tags:
      tags_file: tags.md
markdown_extensions:
  - toc:
      permalink: "#"
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
